name: I_MMSeg
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - wheel==0.44.0=py38h06a4308_0
  - charset-normalizer==3.3.2=pyhd3eb1b0_0
  - torchaudio==2.2.0=py38_cu118
  - ld_impl_linux-64==2.40=h12ee557_0
  - tensorboard-data-server==0.7.0=py38h52d8a92_1
  - llvm-openmp==14.0.6=h9e868ea_0
  - urllib3==2.2.3=py38h06a4308_0
  - requests==2.32.3=py38h06a4308_0
  - xz==5.4.6=h5eee18b_1
  - setuptools==75.1.0=py38h06a4308_0
  - lerc==3.0=h295c915_0
  - pytorch-cuda==11.8=h7e8668a_6
  - yaml==0.2.5=h7b6447c_0
  - tbb==2021.8.0=hdb19cb5_0
  - tk==8.6.14=h39e8969_0
  - torchtriton==2.2.0=py38
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - lame==3.100=h7b6447c_0
  - protobuf==4.25.3=py38h12ddb61_0
  - libabseil==20240116.2=cxx17_h6a678d5_0
  - cuda-version==12.6=3
  - libffi==3.4.4=h6a678d5_1
  - google-auth-oauthlib==0.5.2=py38h06a4308_0
  - mpfr==4.0.2=hb69a4c5_1
  - pysocks==1.7.1=py38h06a4308_0
  - cffi==1.17.1=py38h1fdaa30_0
  - scipy==1.10.1=py38hf6e8229_1
  - zipp==3.20.2=py38h06a4308_0
  - yarl==1.11.0=py38h5eee18b_0
  - jpeg==9e=h5eee18b_3
  - async-timeout==4.0.3=py38h06a4308_0
  - pytorch-mutex==1.0=cuda
  - cuda-libraries==11.8.0=0
  - packaging==24.1=py38h06a4308_0
  - libcurand==10.3.7.77=0
  - pip==24.2=py38h06a4308_0
  - libwebp-base==1.3.2=h5eee18b_1
  - python==3.8.20=he870216_0
  - _libgcc_mutex==0.1=main
  - certifi
  - mkl_fft==1.3.8=py38h5eee18b_0
  - markdown==3.4.1=py38h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - libstdcxx-ng==11.2.0=h1234567_1
  - nettle==3.7.3=hbbd107a_1
  - libunistring==0.9.10=h27cfd23_0
  - cryptography==43.0.0=py38hdda0065_0
  - pillow==10.4.0=py38h5eee18b_0
  - pyyaml==6.0.2=py38h5eee18b_0
  - blinker==1.6.2=py38h06a4308_0
  - libtiff==4.5.1=h6a678d5_0
  - brotli-python==1.0.9=py38h6a678d5_8
  - werkzeug==3.0.3=py38h06a4308_0
  - sqlite==3.45.3=h5eee18b_0
  - lz4-c==1.9.4=h6a678d5_1
  - ffmpeg==4.3=hf484d3e_0
  - ncurses==6.4=h6a678d5_0
  - importlib-metadata==7.0.1=py38h06a4308_0
  - libcublas==11.11.3.6=0
  - libidn2==2.3.4=h5eee18b_0
  - tensorboard==2.12.1=py38h06a4308_0
  - libdeflate==1.17=h5eee18b_1
  - filelock==3.13.1=py38h06a4308_0
  - mkl-service==2.4.0=py38h5eee18b_1
  - pycparser==2.21=pyhd3eb1b0_0
  - pyopenssl==24.2.1=py38h06a4308_0
  - mkl==2023.1.0=h213fc3f_46344
  - jinja2==3.1.4=py38h06a4308_0
  - libcufft==10.9.0.58=0
  - attrs==24.2.0=py38h06a4308_0
  - gmpy2==2.1.2=py38heeb90bb_0
  - appdirs==1.4.4=pyhd3eb1b0_0
  - blas==1.0=mkl
  - multidict==6.0.4=py38h5eee18b_0
  - pyjwt==2.8.0=py38h06a4308_0
  - cuda-cudart==11.8.89=0
  - libnvjpeg==11.9.0.86=0
  - libcufile==1.11.1.6=0
  - google-auth==2.29.0=py38h06a4308_0
  - requests-oauthlib==2.0.0=py38h06a4308_0
  - click==8.1.7=py38h06a4308_0
  - absl-py==2.1.0=py38h06a4308_0
  - pytorch==2.2.0=py3.8_cuda11.8_cudnn8.7.0_0
  - grpcio==1.62.2=py38h6a678d5_0
  - zstd==1.5.6=hc292b87_0
  - aiosignal==1.2.0=pyhd3eb1b0_0
  - sympy==1.13.2=py38h06a4308_0
  - pyasn1-modules==0.2.8=py_0
  - cuda-nvtx==11.8.86=0
  - pooch==1.4.0=pyhd3eb1b0_0
  - cuda-cupti==11.8.87=0
  - re2==2022.04.01=h295c915_0
  - libgfortran5==11.2.0=h1234567_1
  - libgfortran-ng==11.2.0=h00389a5_1
  - aiohttp==3.9.5=py38h5eee18b_0
  - openh264==2.1.1=h4ff587b_0
  - mkl_random==1.2.4=py38hdb19cb5_0
  - networkx==3.1=py38h06a4308_0
  - libtasn1==4.19.0=h5eee18b_0
  - libprotobuf==4.25.3=he621ea3_0
  - mpc==1.1.0=h10f8cd9_1
  - tensorboard-plugin-wit==1.8.1=py38h06a4308_0
  - cuda-nvrtc==11.8.89=0
  - libgomp==11.2.0=h1234567_1
  - openjpeg==2.5.2=he7f1fd0_0
  - _openmp_mutex==5.1=1_gnu
  - idna==3.7=py38h06a4308_0
  - gmp==6.2.1=h295c915_3
  - pyasn1==0.4.8=pyhd3eb1b0_0
  - libgcc-ng==11.2.0=h1234567_1
  - libgrpc==1.62.2=h2d74bed_0
  - cuda-runtime==11.8.0=0
  - lcms2==2.12=h3be6417_0
  - numpy==1.24.3=py38hf6e8229_1
  - zlib==1.2.13=h5eee18b_1
  - mpmath==1.3.0=py38h06a4308_0
  - freetype==2.12.1=h4a9f257_0
  - oauthlib==3.2.2=py38h06a4308_0
  - bzip2==1.0.8=h5eee18b_6
  - readline==8.2=h5eee18b_0
  - frozenlist==1.4.0=py38h5eee18b_0
  - libcusolver==11.4.1.48=0
  - markupsafe==2.1.3=py38h5eee18b_0
  - cachetools==5.3.3=py38h06a4308_0
  - libnpp==11.8.0.86=0
  - libpng==1.6.39=h5eee18b_0
  - openssl
  - libcusparse==11.7.5.86=0
  - ca-certificates
  - rsa==4.7.2=pyhd3eb1b0_1
  - torchvision==0.17.0=py38_cu118
  - libiconv==1.16=h5eee18b_3
  - c-ares==1.19.1=h5eee18b_0
  - gnutls==3.6.15=he1e5248_0
  - pandas[version='>=1.2.0']
